language: csharp
script:
  - xbuild Summit.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore Summit.sln
after_script:
  - nunit-console SummitTests/bin/Debug/SummitTests.dll
notifications:
  email:
    recipients:
      - thewahome.cw@gmail.com
      - v-chgita@microsoft.com
    on_success: always # default: change
    on_failure: always # default: always
